### ISSUE TITLE
Sublime command palette inserts numbers one space before the cursor

### ISSUE THREAD

**Issue by amclain** [duydao/Text-Pastry#16]
There seems to be a bug when using Sublime's command palette to insert numbers. When the command is executed, the numbers are inserted one character behind the cursor. This does not seem to be the case if the Text-Pastry command line is used directly.

Given the following segment of code as an example, the goal is to insert a number before the semicolon: `constant_1 = 101;`

``` text
constant_1 = ;
constant_2 = ;
constant_3 = ;
constant_4 = ;
```

So the first step is to position multiple cursors (illustrated wtih `|`) just before the semicolon, just as you would if you were to start typing more text. Although this may appear obvious, I state it because it is an important issue regarding the bug.

``` text
constant_1 = |;
constant_2 = |;
constant_3 = |;
constant_4 = |;
```

Open Sublime's command palette via `ctrl + shift + p`, select `Text Pastry: Command Line`, and enter `\i101`. The inserted numbers end up _behind_ the cursor location.

``` text
constant_1 =101 ;
constant_2 =102 ;
constant_3 =103 ;
constant_4 =104 ;
```

Running the same command by opening the Text-Pastry command line directly with the respective hotkey (not through Sublime's command palette) works as expected.

``` text
constant_1 = 101;
constant_2 = 102;
constant_3 = 103;
constant_4 = 104;
```

**Comment by Kcko** [comment]
Hi Bro,

sequence i or \i  (not work -- generate only  "i").
When i change this to \i(1) or i1  its works....

it worked in the past, can u tell me why? :]]

Scr: http://files.rjwebdesign.cz/i/20150120-151153---1487x1028---t---pn.png

S pozdravem

Roman Janko
webdesigner & developer

			

gsm: [+420] 777 856 657
email: admin@rjwebdesign.cz <mailto:admin@rjwebdesign.cz>
icq: 176-031-471
www: rjwebdesign.cz <http://rjwebdesign.cz>
linkedin: linkedin.com/in/romanjanko 
<http://www.linkedin.com/in/romanjanko>
twitter: twitter.com/RomanJanko <https://twitter.com/RomanJanko>

			

Rjwebdesign logo

Dne 7.6.2014 v 18:01 Duy Dao napsal(a):

**Comment by duydao** [comment]
Thanks for reporting this issue, I've created #27 for this bug
