### ISSUE TITLE
find REGEX command is case insensitive?

### ISSUE THREAD

**Issue by miusuncle** [duydao/Text-Pastry#30]
When I execute `find user`, `user` are all highlighted, no matter what case it is. Is there any flag to set the case sensitive?

**Comment by duydao** [comment]
Yes, you can use the undocumented switch: --cs (case-sensitive)

```
find user --cs
```

or

```
find --cs user
```

**Comment by miusuncle** [comment]
I've tries it, thanks, it works fine.

**Comment by duydao** [comment]
Glad to help, thanks for using Text Pastry!
