### ISSUE TITLE
`uuid x10` get uuids all in uppercase

### ISSUE THREAD

**Issue by miusuncle** [duydao/Text-Pastry#31]
`uuid` get uuid in lowercase, but `uuid x10` get uuids all in uppercase

**Comment by duydao** [comment]
Thanks, its fixed in 1.4.9

Thanks for using Text Pastry!

**Comment by duydao** [comment]
I've added the switch to the documentation: https://github.com/duydao/Text-Pastry/wiki/Selection-Modifiers
