### ISSUE TITLE
Working scope for `find` and `add` commands

### ISSUE THREAD

**Issue by MuR** [duydao/Text-Pastry#32]
Is it possible to make `find` or `add` commands work only within selected lines of text?

Something like that:
![find_by_regexp](https://cloud.githubusercontent.com/assets/418780/8993668/f8185234-370e-11e5-81fb-319128edd8af.gif)

**Comment by duydao** [comment]
The most common way to achieve this would be:

- Place the Cursor
- Expand selection to lines (CTRL+L or CMD+L)
- Use the Command ```filter 'id': '([^']+)'``` to filter the selected text

Please let me know if that will do it for you. Thanks for using Text Pastry!

**Comment by MuR** [comment]
I've found that package [`selectUntil`](https://github.com/xavi-/sublime-selectuntil) is more suitable for this case.

**Comment by duydao** [comment]
Great, thanks for sharing!
