### ISSUE TITLE
Found patterns not scroll into view

### ISSUE THREAD

**Issue by miusuncle** [duydao/Text-Pastry#33]
When I use `find` command to find some stuff, the found result only shown in status bar. If I ignore the status bar or I hide the status bar, and the found pattern not shown in viewport, it just feels nothing happened. So we can improve the experience one step further -- scroll the first matched pattern into view.

**Comment by duydao** [comment]
I agree! Text Pastry will scroll to the matched pattern *if nothing was found in the visible area* of the file. It will not scroll if there is a match that is already visible.

It would also be usefull if we could navigate through the selections by a shortcut, maybee page up/down when the Text Pastry command line is open. I'll give it a try.

Thanks again for using Text Pastry!
