### ISSUE TITLE
Iterating letters

### ISSUE THREAD

**Issue by mkruselj** [duydao/Text-Pastry#34]
Would be great to have a way to generate letter sequences (A, B, C, D..., a, b, c, d,... perhaps even roman numerals? That might be overkill). When the end of the alphabet is reached, stick another char there (W, X, Y, Z, AA, AB, AC, etc.)

:)

**Comment by duydao** [comment]
Hey!

This is already possible! We can use the [preset](https://github.com/duydao/Text-Pastry/wiki/Command-Line-Reference#presets) "letters" to fill selections, e.g.

```letters c-f```

The letters-preset contains only lower case letters, but you could define a list with upper case letters or use ConverCase to change them afterwards.

Thanks for using Text Pastry!

**Comment by mkruselj** [comment]
Ah, this is cool! Thanks :)
