### ISSUE TITLE
zero padding ?

### ISSUE THREAD

**Issue by tablatronix** [duydao/Text-Pastry#36]
I am trying to do zero padding.

say 
```
C|000002|1
C|000003|1
C|000004|1
C|000005|1
...
C|000100|1
```

`as 0000001 x 300` or similar using a token similar to sprintf `%06d` etc.

**Comment by duydao** [comment]
zero padding is already supported by opening the text pastry command line and using a command like this:

```1 1 6```

You can check out the (command line reference)[https://github.com/duydao/Text-Pastry/wiki/Command-Line-Reference] in the wiki for even more commands

**Comment by tablatronix** [comment]
wonderful, I didn't even see the wki.
