### ISSUE TITLE
Repeating increments not working with letters

### ISSUE THREAD

**Issue by mkruselj** [duydao/Text-Pastry#38]
I wanted Text-Pastry to do this:

A
A
A
B
B
B
C
C
C

I've tried to use "letters 1-3 each=3", but it didn't work. :(

It'd be great if repeating increments would work for not just letters, but anything else, simply by adding the "each" keyword. Of course, if I'm missing something here and this is already possible, I'd love to be corrected (but then also wiki should have examples of this, too :))

Thanks!

**Comment by okitu** [comment]
+1

I just wanted to increment something with hex-values.
Please add custom ranges! numeric, alpha-numeric, hex, ...

**Comment by duydao** [comment]
Hey, thanks for usong Text Pastry!

We can use the x-arg to repeat a loop, but not all commands support it yet.

As for custom ranges: we can use custom lists or a word list for this (let me check the Wiki). Do you have a specific example for this use-case?

**Comment by duydao** [comment]
Repeating words is supported in 1.5.0. This can be done by the x-arg (e.g. x2) or each=2:

```letters 1-3 each=3```

will produce the same result as:

```words a b c x3```
