### ISSUE TITLE
Idea: loop a range within text selection

### ISSUE THREAD

**Issue by mkruselj** [duydao/Text-Pastry#39]
This is similar to using "each" keyword, but a bit differently.

In this idea, let's say we want to generate the same range of values but repeated multiple times. We need to define start value, END VALUE (new!), optionally step size, optionally number of digits, and then repeat it throughout the text selection. Let's call this new keyword "loop"

For example this command:

0 10 2 2 each=2 loop

executed in a selection of 20 rows would result in this:

00
00
02
02
04
04
06
06
08
08
10
10
00
00
02
02
04
04
06
06

Do you think this might be useful? :)

**Comment by duydao** [comment]
Hey, thanks for using Text Pastry!

Yes, this sounds quite usefull. In fact, I've added an x-arg parameter for loops that ahould do exactly that, but its not implemented for all commands yet.

Bare wirh me, I'll add it to the next version!

**Comment by duydao** [comment]
As suggested, I've added a new argument to set the end of a repeatable list:

```0 2 2 end=10 each=2```

We don't need to use a loop keyword, since lists are automatically expanded to match the selection.

**Comment by mkruselj** [comment]
When is 1.5.0 officially out? :)


Thanks for doing this!

**Comment by duydao** [comment]
Hey!

I should be able to release it this week. Still working on #38, works for regular lists but not yet for presets.

Thanks for using Text Pastry!
