### ISSUE TITLE
i love you

### ISSUE THREAD

**Issue by andyperlitch** [duydao/Text-Pastry#40]
that is all. great plugin!

**Comment by duydao** [comment]
Thanks alot  mate, you've made my day! And thanks for using Text Pastry!

**Comment by andyperlitch** [comment]
I'm just kicking myself for not finding it sooner. For all the times I did this...
![before-pastry](https://cloud.githubusercontent.com/assets/1390651/11749822/caa8ec8e-9fe4-11e5-9a26-1a12a1c735b8.gif)
