### ISSUE TITLE
Same UUID on multiple selections?

### ISSUE THREAD

**Issue by JoshRiser** [duydao/Text-Pastry#41]
Currently when I us Sublimes Multiline Selection and run the uuid/UUID command with Text Pastry, it generates different UUIDs for each selection. I understand the reasoning behind this, but is there any way I can make it generate the same UUID on each selection?

**Comment by duydao** [comment]
Hey mate

Unfortunately, there is no switch to reuse the same uuid multiple times. Wouldn't it be easier to copy the uuid and use sublimes multi-paste?

Thanks for using Text Pastry!

**Comment by JoshRiser** [comment]
I can, but I will have to generate one, copy it, and multipaste it almost 200 times for what I am trying to accomplish. It will be tedious but it looks like that is the solution in this case.

Cheers, great plugin otherwise!

**Comment by duydao** [comment]
Thanks for using Text Pastry!
