### ISSUE TITLE
How to increment across multiple files

### ISSUE THREAD

**Issue by s10wen** [duydao/Text-Pastry#44]
What I'd like do is

FROM:
```
file1.txt:
word
word
word
file2.txt:
word
word
word
```

TO:
```
file1.txt:
word1
word2
word3
file2.txt:
word4
word5
word6
```

I got it working with one file thanks to @wesbos (also thanks for pointing me here) :+1: 

Would be great if there was a way to do across multiple files, thanks ^_^

**Comment by duydao** [comment]
Hey,

First, thanks for using Text Pastry!

This sounds interesting. Give me some time to check if multi-window-pastes are easy to implement. I' have another feature prepared to handle scenarios like this, so stay tuned.

Again, thanks for using Text Pastry!

**Comment by s10wen** [comment]
@duydao any luck with this please? Anything I can do to help test?

**Comment by duydao** [comment]
Thanks for getting back to me.

I've had a run with a version that replaced over multiple documents over this weekend, but it doesn't seem to be practical.

The order of the window seems to matter and there were multiple inserts in documents that we won't want. We would have to make sure that the only "pasteable" documents are open and that seems a bit unconvenient.

Do you have a specific use-case for this feature?

**Comment by s10wen** [comment]
@duydao I'm working on a large legacy code base that has multiple templates. Sometimes it can be time consuming to find the correct template to work on. If I can inspect an element, then do a find and replace adding an incremental value, I could then refresh the page and find which template it was related to.

I can always look at alternative ways of doing this via the command line, but it would have been nice if it was possible to it via Sublime Text.

Thanks for having a look anyway :+1:

**Comment by duydao** [comment]
As I mentioned, I have another feature that should do exactly what you're looking for. I'm calling it "paste gun", and if you don't mind to play a beta tester, I can upload the current version to this repo

**Comment by s10wen** [comment]
@duydao cool, yeah, please let me know how to test and I'll give it a go :)

**Comment by duydao** [comment]
are you working on linux, win or mac?

**Comment by s10wen** [comment]
Mac

**Comment by duydao** [comment]
I've just pushed the feature to the develop branch.

- Please disable your Text Pastry Plugin (package control -> disable package)
- Open the packages folder ```Sublime Text > Preferences > Browse Packages```
- Clone the develop branch into that folder ```git clone -b develop git@github.com:s10wen/Text-Pastry.git```
- Restart Text Pastry

You will get a new menu item called ```Paste Gun```
- Open the menu and select ```Show Ammo```
- generate numbers 1-50 by opening the text pastry command line and enter ```1 x50```
- Start pasting by using ```Ctrl-V```

**Comment by s10wen** [comment]
Cloned the branch, where can I see the menu item `Paste Gun`?

**Comment by duydao** [comment]
it should be in Sublime Text, between project and window. Are you using Sublime Text 2 or 3?

**Comment by s10wen** [comment]
3

<img width="131" alt="screen shot 2016-03-22 at 19 54 41" src="https://cloud.githubusercontent.com/assets/1136114/13965862/f36d82a0-f067-11e5-9e5a-caf882890285.png">

**Comment by duydao** [comment]
Please verify the following steps:

- you have disabled/removed the Text Pastry package
- the directory of the cloned project is .../Sublime Text 3/Packages/Text-Pastry
- you are on the branch develop
- you have restarted Sublime Text

**Comment by s10wen** [comment]
yep, `git clone -b develop git@github.com:s10wen/Text-Pastry.git` didn't work though, so I did a `git clone https://github.com/duydao/Text-Pastry.git` then followed this http://stackoverflow.com/questions/10312521/how-to-fetch-all-git-branches to get your branch and switch to it.

**Comment by duydao** [comment]
ok, thanks for verifying!

Did you make the switch to the develop branch by calling "git checkout develop"? You can verify that you are on the right branch by checking for a file called ```text_pastry_clipboard.py```

**Comment by s10wen** [comment]
Appears that I'm on the right branch, but I don't have that file.

**Comment by s10wen** [comment]
Something :fish: going on:
```
warning: refname 'origin/develop' is ambiguous.
warning: refname 'origin/develop' is ambiguous.
```

**Comment by duydao** [comment]
Hmm, could you remove the whole folder and check it out again with:

```git clone -b develop git@github.com:duydao/Text-Pastry.git```

**Comment by s10wen** [comment]
ok, got the correct branch now and can see `Paste Gun` and `Show Ammo`. Did <kbd>Cmd</kbd>+<kbd>Alt</kbd>+<kbd>T</kbd> to get the command line open and put in `1 x50` in there. But I'm not sure what you mean by start pasting?

**Comment by duydao** [comment]
Great!
Ok, this is how it works:
- Paste gun will use every line in the "Clipboard Ammo" window as "Clipboard Data" 
- Create a new file and press ```Ctrl+V``` and the first line will be pasted (```1```)
- Create a new file and press ```Ctrl+V`` and the second line will be pasted (```2```)

**Comment by s10wen** [comment]
Bit confused sorry, I'd like to search and replace on existing files, not create new ones.

**Comment by duydao** [comment]
Hey @s10wen 

Sorry, multiple selection weren't supported in that version. It is now :-)

1.5.0 will be released this week, just some documentation and more testing to do.

Thanks for using Text Pastry!

**Comment by mrwiseowl** [comment]
Hey @duydao did Paste gun ever go public? I'd love to give it a shot, I tried cloning from the developer branch above but got a permission denied.
