### ISSUE TITLE
Number sequence "each"

### ISSUE THREAD

**Issue by LydiaF** [duydao/Text-Pastry#46]
Hi there,

Firstly thanks for text pastry, use it many times every day!

Secondly, I would like to be able to generate a number sequence like:
1 1 2 2 3 3 4 4
Sorry if this is already possible and I haven't seen it. So in text pastry this might be \i(each = 2)

Thanks :)

**Comment by duydao** [comment]
Hey!

Thank you very much for your suggestion! A similar feature was already requested in #39. It will be in release 1.5.0 if everything works out. 

Thanks for using Text Pastry!

**Comment by duydao** [comment]
Hey @LydiaF,

I just realized that this is already possible in the current version of Text Pastry:

i 1 each=2

Thanks again for using Text Pastry!

**Comment by LydiaF** [comment]
Thank you!
