### ISSUE TITLE
Insert nums does not work with "float" step

### ISSUE THREAD

**Issue by amok** [duydao/Text-Pastry#47]
F.i  `1 0.3`, where step - 0.3. That case nothing happens on enter

**Comment by duydao** [comment]
Hi

We are using the python range command to generate the numbers, and atm only integers are supported, sorry.

Check out https://github.com/jbrooksuk/InsertNums, That should do what you're looking for

Thanks for using Text Pastry!

**Comment by amok** [comment]
I'm already using InsertNums but planned to move to Text-Pastry
thank you for the answer!

**Comment by duydao** [comment]
Ah, nice to hear that you're considering Text Pastry! I'll let you know when it's available

**Comment by amok** [comment]
awesome! thanks
