### ISSUE TITLE
TextPastryHistory is not defined / ST3 /

### ISSUE THREAD

**Issue by Kcko** [duydao/Text-Pastry#48]
Hi,
I cant use shortcut alt +b (insert character "{") because TextPastry is screaming: 

"TextPastryHistory is not defined"

I obviously override shortcut in sublime-keymap but TextPastry remember native shortcut defined in plugin.

Can you help me?

Screenshots:
![](http://files.rjwebdesign.cz/i/20160518-100143.png)
![](http://files.rjwebdesign.cz/i/20160518-100201.png)

**Comment by duydao** [comment]
Hi

You should be able to overwrite the key binding through your user keybindings file.

The error is worries me, I'll check it out.

Thanks for using Text Pastry!

**Comment by Kcko** [comment]
Hi DuyDao,


it should be ..., but it does not work with :), it seems to be like a bug ...
with others plugins i have no problem with overriding key-mapping.

Can you help me how to do it? I want to use ur great plugin, but need more use ctrl alt b :)

**Comment by Kcko** [comment]
So what? Or how to remove "pastry history action"? Overriding not working :(

**Comment by Kcko** [comment]
Any progress pls?

**Comment by duydao** [comment]
Hi @Kcko 

Yeah, I've tried to rebind alt+b and ctrl+alt+b to the swirly brace and it works without problems. To verify that it **is** a problem with Text Pastry, you could disable the plugin and try again.

**Comment by duydao** [comment]
You could also use AutoHotKey to do key bindings:  https://autohotkey.com/
