### ISSUE TITLE
1.5 release?

### ISSUE THREAD

**Issue by princemaple** [duydao/Text-Pastry#52]
Hi,

Just wondering, why was 1.5 "released" in May but never *really released*?

**Comment by duydao** [comment]
Hey, I wanted to do some additional testing and documenting, that was some of the reasons.

I've been using 1.5.0 for a while now, I've just tagged it. It will be available in a couple of hours.

Thanks for reminding me, and thanks alot for using Text Pastry!

**Comment by princemaple** [comment]
Thanks for the awesome package!
