### ISSUE TITLE
\i(N,M) not work on  sublime 3 in  windows 8

### ISSUE THREAD

**Issue by eromoe** [duydao/Text-Pastry#53]
Hi, this plugin is really awesome.
Because the default shortcut `ctrl + alt + n` is conflict with Evernote's create new note shortcut, I'd like to use `ctrl + alt +t`. But I find it cannot excute pattern like `1 1 3`  except already type it once  in  `ctrl + alt + n` as history command. Then I tried `\i(1,2)` which not works, though `\i`  and `\i0` does.

**Comment by duydao** [comment]
Hi

You can remap the keys to anything you want. You can find the default key map as an example here:

https://github.com/duydao/Text-Pastry/blob/master/Default%20(Linux).sublime-keymap

for more information on key bindings, you could check out:

http://docs.sublimetext.info/en/latest/customization/key_bindings.html

Another way to open Text Pastry is to use the _Command Palette_ (Ctrl+Shift+P).

I've just tried to use \i(1,2), it worked as expected (giving 1 3 5 7 etc). Please remember that this is  only useful if you have multiple selections.

If you want to provide some infos about your environment, you can reopen this issue and I'll be happy to help (platform, version of sublime, version of text pastry, console info)

Thanks a lot for enjoying Text Pastry!

**Comment by eromoe** [comment]
I think I found the problem:
![qq 20161104102857](https://cloud.githubusercontent.com/assets/3938751/19992521/9b5652b2-a279-11e6-90f9-945d15466c61.png)

I was tring to type `\i(1,2)` on that input box which popuped by  `ctrl + alt + t` , it wouldn't work in this way.
It need Enter menu  ` \i(,N,M)`  first, then replace `N, M` in `Text Pastry Command:` input box：
![qq 20161104103301](https://cloud.githubusercontent.com/assets/3938751/19992589/1a2eecf2-a27a-11e6-89b5-4d212c3689ba.png),  just feel a little inconvenient. 

PS: partern such as `\i(01,1)`  would not print as  `01, 02, 03 ....` , is it by design?

**Comment by duydao** [comment]
Thanks for the clarification.

The Text Pastry Menu is only a filter for the items displayed in the list (thats how sublime text menus work). What you're looking for ist the text pastry command line. You can navigate through the history with arrow up/down to repeat commands.

There is a syntax for padding, its the third argument (e.g. \i(1,1,2) or 1 1 2). In this context, 2 means  the number of digits that should be padded. You can also check out the wiki for examples:

https://github.com/duydao/Text-Pastry/wiki/Examples#insert-nums-syntax
