### ISSUE TITLE
Group restart sequence

### ISSUE THREAD

**Issue by stegrams** [duydao/Text-Pastry#55]
I m not sure how - or if - it is possible (an enhancement perhaps).
Here is a sample of an XML file.
```xml
<person>
  <name>Jane</name>
  <item>wallet</item>
  <item>car</item>
  <item>tv</item>
  <item>cellphone</item>
</person>
<person>
  <name>Chris</name>
  <item>pc</item>
  <item>cat</item>
</person>
```
I d like enumeration to restart somehow on each persons group of items like this
```xml
<person>
  <name>Jane</name>
  <item1>wallet</item1>
  <item2>car</item2>
  <item3>tv</item3>
  <item4>cellphone</item4>
</person>
<person>
  <name>Chris</name>
  <item1>pc</item1>
  <item2>cat</item2>
</person>
```

**Comment by duydao** [comment]
Hi @stegrams

This is already possible:

- Select all item words with CMD / CTRL + D from the first group
- move the cursor to the end of the item word
- use the following command in the _Text Pastry_ command line: `1 each=2`

_Text Pastry_ will repeat item of the sequence starting at 1. Repeat the steps for the next block.

Let me know if this helps and thanks a lot for using Text Pastry!

**Comment by stegrams** [comment]
```each=``` is a nice feature! I didnt noticed!

About my question.
Is not very practical to select each block manually. You see I don't talk about 2 blocks - as my example falsy suggest  - but hundreds or even thousands.

I thought it may be a way to set a "restart numbering when the next selection has a distance of more than N lines from the previous one" with a customized N.

**Comment by duydao** [comment]
Actually, I'm working for a while on context sensitive sequences. Pretty sure that we could achieve it by using the shell functionality of _Text Pastry_.

I'll make some tests and will get back to you!

**Comment by SmartManoj** [comment]
[Workaround](http://smartmanoj.blogspot.com/2018/06/how-to-create-sublimetext-plugin.html)

**Comment by stegrams** [comment]
Thank you @SmartManoj for sharing your solution.
I ve tested your workaround and works like a charm!

Although for me, the habit of creating from time to time, case specific plugins is a bit overwhelming.

Anyway, I really appreciate for your time :+1:
