### ISSUE TITLE
add/reduce/filter by regex does not use regex

### ISSUE THREAD

**Issue by timLinscott** [duydao/Text-Pastry#56]
The "Add selection by regex...", "Reduce selection by regex...", and "Filter selection by regex..." commands don't actually use regex searches, just plaintext searches.

**Comment by duydao** [comment]
Thanks for using Text Pastry!

Could you provide an example, I will look into it asap

**Comment by timLinscott** [comment]
I tried using "Reduce selection by regex" on `(this, is, a, list)` using the search term `\(|\)|, ` and nothing changed. Is there a parameter that toggles regex that I'm missing?

**Comment by duydao** [comment]
I've just created a fix for this issue, it should be available in a few hours by package control. Thanks for using Text Pastry!
