### ISSUE TITLE
Math with your selection?

### ISSUE THREAD

**Issue by gonchar** [duydao/Text-Pastry#58]
Hello!

Is it possible to do math and use functions like sin/cos/ceil/floor and etc and apply it to my selection?

Thank you!

**Comment by duydao** [comment]
Hey @gonchar

I think this is possible with the shell functionality. Can you give me more infos to your setup (win/mac or linux, sublime 2/3, node/python/bash available?)

Thanks for using Text Pastry!

**Comment by gonchar** [comment]
Mac OSX, Sublime 3

**Comment by duydao** [comment]
I've just found https://github.com/jbrooksuk/Sublime-Evaluate, it should do what you're looking for!

Thanks for using Text Pastry!
