### ISSUE TITLE
Missing On Package Manager

### ISSUE THREAD

**Issue by jayfunk** [duydao/Text-Pastry#59]
I am unable to install the package from the package manager. I am seeing this on the package manager website.

![screen shot 2017-07-17 at 2 38 07 pm](https://user-images.githubusercontent.com/2545666/28286421-b71f06ae-6afd-11e7-9c3a-14dee182d587.png)

**Comment by duydao** [comment]
Hi @jayfunk 

I think this was a temporary github/packagecontrol problem since it looks good atm :-)

Thanks for using Text Pastry!
