### ISSUE TITLE
increment selected numbers

### ISSUE THREAD

**Issue by jankuehn** [duydao/Text-Pastry#63]
Hi,

first of all great tool! I'm just missing one feature or I'm not sure if it's already there.
With this selection:
1|
2|
2|
3|
I'd lile to have this result:
2|
3|
3|
4|

Meaning: I wnat to add 1 (or any number) to each selected number. Is that at all possible or in any way planned as a new feature?

Best regards,
Jan

**Comment by duydao** [comment]
HI @jankuehn 

Yes, there is a way to do this my using the node / python configuration (which is a bit inconvenient tbh).

I'll add an operator for doing this.

Thanks for using Text Pastry!

**Comment by SmartManoj** [comment]
You can use emmet package. Ctrl up to increment

**Comment by sergeevabc** [comment]
Err...

2022-226
2022-311
2023-002

I have selected a column with 226,311,002.
Which command should I use to get values incremented +1 (226,312,003)?

**Comment by duydao** [comment]
Hi @sergeevabc,

this is not possible with Text Pastry, but there are some Plugins that can help you with this.

As example:

https://packagecontrol.io/packages/Increment%20Decrement

Thanks for using Text Pastry!
