### ISSUE TITLE
New lines On the fly

### ISSUE THREAD

**Issue by SmartManoj** [duydao/Text-Pastry#64]
Eg: 1 x5
Expected Behaviour: 
    1|
    2|
    3|
    4|
    5|
Actual Behaviour : 
    1|

**Comment by scholtes** [comment]
`1 x5` does not declare a bounded list from 1 to 5.  It declares an incrementing generator (e.g., `1, 2, 3, 4, ...`), except that each element is consecutively repeated 5 times.  E.g., `1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3 ...`. 

Text-Pastry iterates through generators by inserting each next element into each cursor position.  If you only have the cursor placed at one position, you will only get the first element of the generator.

**Comment by SmartManoj** [comment]
https://github.com/duydao/Text-Pastry/blob/master/RELEASENOTES.md#repeat-argument-x-arg

**Comment by SmartManoj** [comment]
s 1 x5
