### ISSUE TITLE
add selection max limit

### ISSUE THREAD

**Issue by himura-hg** [duydao/Text-Pastry#65]
It seems there is a maximum limit of the iterations the `add TEXT` command does. 

Some times it selects 70 lines that contain that text, others, 80 or maximum 146

I tried to use this in a log file with 144098 lines, what is the maximum lines limit for selecting specific text ?

**Comment by duydao** [comment]
@himura-hg There is no code limitation, but certainly there is a limitation regarding memory. I will check the implementation. How big is your file?

**Comment by himura-hg** [comment]
Hello @duydao thanks for following up, 
I have seen this issue with files ranging from 6K to 40K lines, I mostly used the Text-Pastry to add and highlight several similar lines that are repetitive in log files and to remove them or do operations with them. 

This does not occurs for example if at the same file I use Sublime's built in find and use regular expression to attempt to replicate similar behavior.

**Comment by duydao** [comment]
Hi @himura-hg, there is indeed a [configurable file size limitation](https://github.com/duydao/Text-Pastry/blob/master/TextPastrySelection.sublime-settings#L12) for that feature. You can change it by creating TextPastrySelection.sublime-settings in your user directory (Browse Packages -> User) and setting the threshold value. The value represents megabytes:

```json
{
    "preview_file_size_threshold": 100
}
```

Thanks for using text pastry!
