### ISSUE TITLE
"1 x5" no longer generates 5 lines

### ISSUE THREAD

**Issue by curtisyallop** [duydao/Text-Pastry#68]
"1 x5" (on a blank line with no selection) results in "1". The "x5" part does not work.

"1 end=1 x5" does work, oddly. "1 1 1 x5" does not. "range 1 5" and "range 1 1 x5" work.

RELEASENOTES.md says "1 x 5" will generated 5 lines under section "Repeat argument (x-arg)".

I am using version 1.5.1.

**Comment by SmartManoj** [comment]
s 1 x5 #64

**Comment by niftinessafoot** [comment]
This works, but what is `s`? I’m not finding it documented anywhere.

**Comment by SmartManoj** [comment]
alias for `as `

**Comment by duydao** [comment]
We had to change this syntax in order to make it parsable form the command line. Please use s 1 x5 as suggested. For a reference, please take a look at this:

https://github.com/duydao/Text-Pastry/blob/master/config/TextPastryCommands.json#L118
