### ISSUE TITLE
How to escape number in AutoStep(as) command

### ISSUE THREAD

**Issue by SmartManoj** [duydao/Text-Pastry#69]
Eg: as 1,2 x3
Actual Behaviour :
1,2
2,3
3,4
How to achieve this ?
1,2
2,2
3,2

Is there something like \2 to escape the number?

**Comment by duydao** [comment]
Hi there, I don’t think I understand your example. Could you explain the use case? Would it be possible for you to just select the number that you would like to change?

Thanks for using Text Pastry!

**Comment by SmartManoj** [comment]
@duydao  Edited Now
