### ISSUE TITLE
piping bag does not work

### ISSUE THREAD

**Issue by jakemkc** [duydao/Text-Pastry#78]
Hi,

I tried to follow the instruction to use the piping feature to incrementally modify content of multiple text files as follow:

> Open the command palette and look for "Text Pastry: Show Piping Bag" or open Tools -> Text Pastry -> Show Piping Bag.
> 
> CMD + Shift + P -> Text Pastry: Generate a list of numbers from 1 to 100
> 
> Open a file
>
> Make 4 selections
>
> Open the command palette and select Text Pastry: Pipe into selections
 

text pastry will only replace the 1st selection with the first number in the piping bag.

I wonder am I missing something here?

I am using MacOS 10.13.3
sublime 3.1.1

thanks!

**Comment by duydao** [comment]
Hi @jakemkc,

This seems to be a bug, I'll check it out.

Thanks for using Text Pastry!
