### ISSUE TITLE
Descending/countdown number range - no START

### ISSUE THREAD

**Issue by JetStarBlues** [duydao/Text-Pastry#80]
I wish to create a key binding that generates a descending number range that ends with zero ( END = 0, STEP = -1). For example:
```
bit3
bit2
bit1
bit0
```
However, reading the [Wiki page](https://github.com/duydao/Text-Pastry/wiki/Number-Range), it seems that the START parameter is required.  This however makes setting a key binding for this scenario impossible and also requires the user to count the number of lines (minus 1) to input as the START command when using the command line.

Given an END and STEP, can the code be modified to automatically compute the START?

**Comment by duydao** [comment]
Hi @JetStarBlues, this option will be supported in 1.6.0!

**Comment by duydao** [comment]
Duplicate #61
