### ISSUE TITLE
Find, replace, increment

### ISSUE THREAD

**Issue by jitccgcg** [duydao/Text-Pastry#82]
If I have:

let myModel = Model(CreatedOn: "2018-06-04T14:11:44Z", id: "1")

and I want to create 100 of these, but increment the value of id for occurrence of `id: "1"`, how can I do this?

**Comment by duydao** [comment]
Hi @jitccgcg,

I would copy the line 100 times, multiselect the 1 (select all, cmd+shift+l to select each line and then navigate to the 1 by using the left arrow), and then use text pastry to insert the numbers from 1 to X.

Thanks for using Text Pastry!
