### ISSUE TITLE
Step Sequence

### ISSUE THREAD

**Issue by craigerskine** [duydao/Text-Pastry#85]
Is there a way to step the numeric increment to a certain point and then start over again? I need to select hundreds of lines and I want them to count from 100-900 in increments of 100, but when it reaches 900 the next items should start back over again at 100. Any help would be greatly appreciated.

100
200
300
400
500
600
700
800
900
100
200
300
400
500
600
700
800
900
...

**Comment by duydao** [comment]
@craigerskine You could use the range command, it repeats after reaching the max value:

range 100 900 100

https://github.com/duydao/Text-Pastry/wiki/Number-Range
