### ISSUE TITLE
Appreciation for Text Pastry

### ISSUE THREAD

**Issue by gregsadetsky** [duydao/Text-Pastry#88]
Hey, sorry to pollute the issues, but I just wanted express gratitude & thanks for Text Pastry!

Every time I do a multi line select in Sublime and paste 0 to X integers... it feels like magic! Ha. Thanks so much

All the best!

**Comment by duydao** [comment]
Hi @gregsadetsky,

Thank you very much, I really appreciate it!

Thanks for using Text Pastry & happy hollidays
