### ISSUE TITLE
How to run a multiplication calculation ?

### ISSUE THREAD

**Issue by SuSuSoo** [duydao/Text-Pastry#90]
I need to generate a number similar to the following, how should I write the command ?

```
int(1)
int(2)
int(4)
int(8)
int(16)
int(32)
...
```

**Comment by duydao** [comment]
Hi,

this isn't possible at the moment.

My suggestion would be to generate the list in your favourite language and generate the list

For example https://www.programiz.com/python-programming/online-compiler/
```python
numbers_sizes = (2**i for i in range(1, 10))
for n in numbers_sizes:
    print(n)
```
results in this:

```
2
4
8
16
32
64
128
256
512
```

Thanks for using Text Pastry!
